<a href="https://colab.research.google.com/github/kuldeepkhas18/Data.Science.nf/blob/main/Data.Science.nf/module.2/homework/Data_clean_code_ipnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Cleaning Step

In [1]:
import pandas as pd

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Messy_Employment_India_Dataset.csv to Messy_Employment_India_Dataset.csv

#Employment of India Dataset - Data Cleaning Project

##This notebook performs complete data cleaning on the Messy Employment India Dataset using 10 standard data-cleaning steps.

##Step 2: Load and inspect dataset

In [4]:
df = pd.read_csv("Messy_Employment_India_Dataset.csv")

##Step 3: Understand Dataset Structure and Data Types

In [5]:
df.dtypes

Status                   object
Age Group                object
Education                object
Industry                 object
Location                 object
AI Risk                  object
Years of Experience     float64
Monthly Salary (INR)    float64
Date Recorded            object
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

In [7]:
df.shape

(2000, 9)

In [8]:
df.columns

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')

In [9]:
df.index

RangeIndex(start=0, stop=2000, step=1)

In [10]:
df.isnull()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,False,False,False,False,False,True,True,False,False
1,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,True,False,False
1996,False,False,False,False,True,True,False,False,False
1997,True,False,False,False,True,False,True,False,False
1998,False,False,False,False,False,False,False,False,False
1999,False,False,False,True,True,False,True,False,False

In [11]:
df.isnull().sum()

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [12]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.describe()

       Years of Experience  Monthly Salary (INR)
count           980.000000           1613.000000
mean             15.244898          76886.360818
std               9.103941          41628.008054
min               0.000000           5100.000000
25%               7.000000          40700.000000
50%              16.000000          77200.000000
75%              23.000000         112400.000000
max              30.000000         149900.000000

##Step 4: Identify missing values

In [15]:
df.isnull().sum()

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [16]:
df['Years of Experience'] = df['Years of Experience'].fillna(df['Years of Experience'].median())
df['Monthly Salary(INR)'] = df['Monthly Salary (INR)'].fillna(df['Monthly Salary (INR)'].median())

In [17]:
Col=[
    'status','Age Group','Education','Indurstry','Location','AI Rist'
]
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].median())

In [18]:
df.isnull().sum()

Status                  0
Age Group               0
Education               0
Industry                0
Location                0
AI Risk                 0
Years of Experience     0
Monthly Salary (INR)    0
Date Recorded           0
Monthly Salary(INR)     0
dtype: int64

In [19]:
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded,Monthly Salary(INR)
0,EMPLOYED,25_34,high school,Technology,Urban,HIGH,16.0,40700.0,1/1/2023,40700.0
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,16.0,17500.0,1/2/2023,17500.0
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023,77600.0
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023,100200.0
4,Employed,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023,19500.0
...,...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,16.0,113000.0,6/18/2028,113000.0
1996,EMPLOYED,25-34,PhD,Tech,Bangalore,HIGH,22.0,102200.0,6/19/2028,102200.0
1997,Employed,35 - 44,Masters,Education,Bangalore,low,16.0,31600.0,6/20/2028,31600.0
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028,92500.0
1999,UNEMPLOYED,25_34,High School,Retail,Bangalore,moderate,16.0,43300.0,6/22/2028,43300.0

##Step 5: Remove duplicate records

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df = df.drop_duplicates()

In [22]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

##Step 6: Correct inconsistent text formatting

In [23]:
text_columns = df.select_dtypes(include="object").columns
for col in text_columns:
    df[col] = df[col].str.strip().str.title()

In [24]:
df['Education'].value_counts()

Education
Bachelors      421
High School    377
Masters        217
Diploma        204
Phd            201
Bachelor'S     200
Ph.D           199
Master         181
Name: count, dtype: int64

In [25]:
df['Education'] = df['Education'].replace({
    'Bachelor\'s': 'Bachelors',
    'Master': 'Masters',
    'Phd': 'PhD',
    'Ph.D': 'PhD'
})

In [26]:
df["Age Group"] = df["Age Group"].astype(str).str.strip()

df["Age Group"] = df["Age Group"].replace({
    "18 to 24": "18-24",
    "25_34": "25-34",
    "35 - 44": "35-44"
})

In [27]:
print(df["Age Group"].unique())

['25-34' '18-24' '45-54' '35-44' '55+' '18 To 24']

In [28]:
df["Age Group"] = df["Age Group"].replace({
    "18 To 24": "18-24"
})

In [29]:
print(df["Age Group"].unique())

['25-34' '18-24' '45-54' '35-44' '55+']

##Step 7: Fix data type issues

In [30]:
df.dtypes

Status                   object
Age Group                object
Education                object
Industry                 object
Location                 object
AI Risk                  object
Years of Experience     float64
Monthly Salary (INR)    float64
Date Recorded            object
Monthly Salary(INR)     float64
dtype: object

In [31]:
df['Date Recorded']=pd.to_datetime(df['Date Recorded'])

In [32]:
df.dtypes

Status                          object
Age Group                       object
Education                       object
Industry                        object
Location                        object
AI Risk                         object
Years of Experience            float64
Monthly Salary (INR)           float64
Date Recorded           datetime64[ns]
Monthly Salary(INR)            float64
dtype: object

##Step 8: Detect and handle outliers

In [33]:
df['Monthly Salary (INR)'].describe()

count      2000.00000
mean      76947.05000
std       37382.13816
min        5100.00000
25%       49150.00000
50%       77200.00000
75%      104125.00000
max      149900.00000
Name: Monthly Salary (INR), dtype: float64

##Step 9: Rename and Standardize Column Names

In [34]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [35]:
df.columns

Index(['status', 'age_group', 'education', 'industry', 'location', 'ai_risk',
       'years_of_experience', 'monthly_salary_(inr)', 'date_recorded',
       'monthly_salary(inr)'],
      dtype='object')

In [36]:
df.rename(columns={"monthly_salary(inr)": "monthly_salary"}, inplace=True)

In [37]:
df.columns

Index(['status', 'age_group', 'education', 'industry', 'location', 'ai_risk',
       'years_of_experience', 'monthly_salary_(inr)', 'date_recorded',
       'monthly_salary'],
      dtype='object')

##Step 10: Validate cleaned data

In [38]:
df.isnull().sum()

status                  0
age_group               0
education               0
industry                0
location                0
ai_risk                 0
years_of_experience     0
monthly_salary_(inr)    0
date_recorded           0
monthly_salary          0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   status                2000 non-null   object
 1   age_group             2000 non-null   object
 2   education             2000 non-null   object
 3   industry              2000 non-null   object
 4   location              2000 non-null   object
 5   ai_risk               2000 non-null   object
 6   years_of_experience   2000 non-null   float64
 7   monthly_salary_(inr)  2000 non-null   float64
 8   date_recorded         2000 non-null   datetime64[ns]
 9   monthly_salary        2000 non-null   float64
dtypes: datetime64[ns](1), float64(3), object(6)
memory usage: 156.4+ KB

In [41]:
df.head(5)

,status,age_group,education,industry,location,ai_risk,years_of_experience,monthly_salary_(inr),date_recorded,monthly_salary
0,Employed,25-34,High School,Technology,Urban,High,16.0,40700.0,2023-01-01,40700.0
1,Employed,18-24,Diploma,Fintech,Rural,Moderate,16.0,17500.0,2023-01-02,17500.0
2,Employed,25-34,High School,Retail,Delhi,Low,16.0,77600.0,2023-01-03,77600.0
3,Unemployed,18-24,Masters,Retail,Urban,Low,30.0,100200.0,2023-01-04,100200.0
4,Employed,45-54,Diploma,Fintech,Hyderabad,Low,9.0,19500.0,2023-01-05,19500.0

In [42]:
df.to_csv("Cleaned_Employment_India_Dataset.csv", index=False)

In [43]:
from google.colab import files
files.download("Cleaned_Employment_India_Dataset.csv")