<a href="https://colab.research.google.com/github/kuldeepkhas18/Data.Science.nf/blob/main/Data.Science.nf/module.2/Classwork/module2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

##DATA MANIPULATION WITH PANDAS

#-> SERIES

#Type checking

In [ ]:
l1 = [2,4,6,8,10]
var = pd.Series(l1)
print(var)
print(type(var))

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

#Changing indexing

In [ ]:
l1 = [2,4,6,8,10]
var = pd.Series(l1, index = ["a","b","c","d","e"])
print(var)

a     2
b     4
c     6
d     8
e    10
dtype: int64

#changing datatype

In [ ]:
l1 = [2,4,6,8,10]
var = pd.Series(l1, dtype = "float")
print(var)

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
dtype: float64

#assigning name to file

In [ ]:
l1 = [2,4,6,8,10]
var = pd.Series(l1, dtype = "float", name = "Pandasfile")
print(var)

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
Name: Pandasfile, dtype: float64

#same value at every index

In [ ]:
var2 = pd.Series(5, index = [1,2,3,4,5])
print(var2)

1    5
2    5
3    5
4    5
5    5
dtype: int64

#only same index value add

In [ ]:
var2 = pd.Series(5, index = [2,7,9,13,15])
var3 = pd.Series(10, index = [1,5,9,11,13])
print(var2+var3)

1      NaN
2      NaN
5      NaN
7      NaN
9     15.0
11     NaN
13    15.0
15     NaN
dtype: float64

#converting dictionary to series

In [ ]:
mydic = {
    "name" : "A",
    "rollno": 21,
    "age" : 22,
}
var4 = pd.Series(mydic)
print(var4)

name       A
rollno    21
age       22
dtype: object

#converting list to series

In [ ]:
mydic = {
    "name":["A", "B", "C"],
    "rollno": [21, 22, 25],
    "age": [22, 20, 25],
}
var5 = pd.Series(mydic)
print(var5)

name         [A, B, C]
rollno    [21, 22, 25]
age       [22, 20, 25]
dtype: object

#Sum of series element

In [ ]:
myseries= [ 2,3,4,5,6]
v =pd.Series(myseries)
sum = v.sum()
print("Sum of Serires :", sum)

Sum of Serires : 20

#Mean of series elemen

In [ ]:
myseries= [ 2,3,4,5,6]
v =pd.Series(myseries)
mean = v.mean()
print("Mean of Serires :", mean)

Mean of Serires : 4.0

#Max of series element

In [ ]:
myseries= [ 2,3,4,5,6]
v =pd.Series(myseries)
max = v.max()
print("Max of Serires :", max)

Max of Serires : 6

#Min of series element

In [ ]:
myseries= [ 2,3,4,5,6]
v =pd.Series(myseries)
min = v.max()
print("Min of Serires :", min)

Min of Serires : 6

#Indexing and slicing

In [ ]:
myseries= [ 2,3,4,5,6]
v =pd.Series(myseries)
s1 = v[0]
print(s1)
s2 =v[1:3]
print(s2)

2
1    3
2    4
dtype: int64

#Vectorized Operation

In [ ]:
list1 = [1,2,3,4]
var = pd.series(list1)

AttributeError: module 'pandas' has no attribute 'series'

#-> DATAFRAME

In [ ]:
import pandas as pd

list = [2,4,6,8,10]
df = pd.DataFrame(list)
print(df)
print(type(df))

    0
0   2
1   4
2   6
3   8
4  10
<class 'pandas.core.frame.DataFrame'>

#INDEXING

In [ ]:
info = {
    "name" : "Arpit",
    "Age" : 20,
    "Marks" : 90.5,
    "Status" : True
}
df = pd.DataFrame(info, index = ["A","B","C"])
print(df)

    name  Age  Marks  Status
A  Arpit   20   90.5    True
B  Arpit   20   90.5    True
C  Arpit   20   90.5    True

#LIST

In [ ]:
info = {
    "name" : ["Arpit", "Tanishq", "Sonam"],
    "Age" : [20, 23, 24],
    "Marks" : [90.5, 90.3, 90.9],
    "Status" : True
}
df = pd.DataFrame(info)
print(df)

      name  Age  Marks  Status
0    Arpit   20   90.5    True
1  Tanishq   23   90.3    True
2    Sonam   24   90.9    True

#COLUMNS

In [ ]:
info = {
    "name" : ["Arpit", "Tanishq", "Sonam"],
    "Age" : [20, 23, 24],
    "Marks" : [90.5, 90.3, 90.9],
    "Status" : True
}
df = pd.DataFrame(info, columns = ["name", "Marks"])
print(df)

      name  Marks
0    Arpit   90.5
1  Tanishq   90.3
2    Sonam   90.9

#INDEX VALUE

In [ ]:
info = {
    "name" : ["Arpit", "Tanishq", "Sonam"],
    "Age" : [20, 23, 24],
    "Marks" : [90.5, 80, 98],
    "Status" : True
}
df = pd.DataFrame(info)
print(info['name'][2])

Sonam

#NESTED LIST

In [ ]:
list1 = [["A","B","C","D"],["a", "b", "c", "d"]]
df = pd.DataFrame(list1)
print(df)

   0  1  2  3
0  A  B  C  D
1  a  b  c  d

#Dataframe from Series

In [ ]:
SR = {
     "S" :pd.Series([2,4,6,8,10]),
     "R" :pd.Series(["a","b","c","d","e"])
}
df = pd.DataFrame(SR)
print(df)

    S  R
0   2  a
1   4  b
2   6  c
3   8  d
4  10  e

#Create Column from Previous columns

In [ ]:
df = pd.DataFrame({ 'A': [2,4,6,8,], 'B':[3,5,7,9]})
df ['C'] = df['A'] + df['B']
df

   A  B   C
0  2  3   5
1  4  5   9
2  6  7  13
3  8  9  17

#Comparing Values

In [ ]:
df = pd.DataFrame({ 'A': [2,4,6,8,], 'B':[3,5,7,9]})
df ['C'] = df['A'] + df['B']
df['try']= df['A'] > 4
df[ 'try2'] = df['C']<5
df

   A  B   C    try   try2
0  2  3   5  False  False
1  4  5   9  False  False
2  6  7  13   True  False
3  8  9  17   True  False

#inserting columns

In [ ]:
df = pd.DataFrame ({'A': [1,2,3,4]})
df.insert(1, "name", df["A"])
df.insert(2, "name2", ["A", "B", "C", "D"])
df

   A  name name2
0  1     1     A
1  2     2     B
2  3     3     C
3  4     4     D

In [ ]:
Df1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
Df2= pd.DataFrame( { 'A': [1,2,3,4], 'D': ['a','b','c','d']})
pd.merge(Df1,Df2)

   A  B  D
0  1  A  a
1  2  B  b
2  3  C  c
3  4  D  d

"""On and How

#Inner
"""

In [ ]:
Df1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
Df2= pd.DataFrame( { 'A': [1,2,3,4], 'C': ['a','b','c','d']})
pd.merge(Df1,Df2, on='A', how='inner', indicator=True)

   A  B  C _merge
0  1  A  a   both
1  2  B  b   both
2  3  C  c   both
3  4  D  d   both

#Outer

In [ ]:
Df1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
Df2= pd.DataFrame( { 'A': [1,2,3,4], 'C': ['a','b','c','d']})
pd.merge(Df1,Df2, on='A', how='outer',indicator=True)

   A  B  C _merge
0  1  A  a   both
1  2  B  b   both
2  3  C  c   both
3  4  D  d   both

#Left

In [ ]:
Df1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
Df2= pd.DataFrame( { 'A': [1,2,3,4], 'C': ['a','b','c','d']})
pd.merge(Df1,Df2, on='A', how='left',indicator=True)

   A  B  C _merge
0  1  A  a   both
1  2  B  b   both
2  3  C  c   both
3  4  D  d   both

#Righ

In [ ]:
Df1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
Df2= pd.DataFrame( { 'A': [1,2,3,4], 'C': ['a','b','c','d']})
pd.merge(Df1,Df2, on='A', how='right',indicator=True)

   A  B  C _merge
0  1  A  a   both
1  2  B  b   both
2  3  C  c   both
3  4  D  d   both

In [ ]:
Df1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
Df2= pd.DataFrame( { 'A': [1,5,7,3], 'C': ['a','b','c','d']})
pd.merge(Df1,Df2, on='A', how='right')

   A    B  C
0  1    A  a
1  5  NaN  b
2  7  NaN  c
3  3    C  d

#SUFFIX

In [ ]:
Df1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': ['A','B','C','D','E']})
Df2= pd.DataFrame( { 'A': [1,2,3,4,5], 'C': ['a','b','c','d','e']})
pd.merge(Df1,Df2, left_index=True , right_index=True)

   A_x  B  A_y  C
0    1  A    1  a
1    2  B    2  b
2    3  C    3  c
3    4  D    4  d
4    5  E    5  e

In [ ]:
Df1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': ['A','B','C','D','E']})
Df2= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': ['a','b','c','d','e']})
pd.merge(Df1,Df2, left_index=True , right_index=True , suffixes=('_2019', '_2020'))

   A_2019 B_2019  A_2020 B_2020
0       1      A       1      a
1       2      B       2      b
2       3      C       3      c
3       4      D       4      d
4       5      E       5      e

#JOIN IN PANDAS DATAFRAM

In [ ]:
D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
D2= pd.DataFrame( { 'C': [1,2,3,4], 'D': ['a','b','c','d']})
D1.join(D2)

   A  B  C  D
0  1  A  1  a
1  2  B  2  b
2  3  C  3  c
3  4  D  4  d

##D2 IS PRIMARY AND D1 IS SECONDAR

In [ ]:
D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
D2= pd.DataFrame( { 'C': [1,2,3,4], 'D': ['a','b','c','d']})
D2.join(D1)

   C  D  A  B
0  1  a  1  A
1  2  b  2  B
2  3  c  3  C
3  4  d  4  D

##INDEX IN JOIN

In [ ]:

D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']}, index= ['a','b', 2 , 'd'])
D2= pd.DataFrame( { 'C': [1,2,3,4], 'D': ['a','b','c','d']})
D1.join(D2)

   A  B    C    D
a  1  A  NaN  NaN
b  2  B  NaN  NaN
2  3  C  3.0    c
d  4  D  NaN  NaN

##value of C and D in revers

In [ ]:

D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']}, index= ['a','b', 'c' , 'd'])
D2= pd.DataFrame( { 'C': [1,2,3,4], 'D': ['a','b','c','d']}, index= ['d','c', 'b' , 'a'])
D1.join(D2)

   A  B  C  D
a  1  A  4  d
b  2  B  3  c
c  3  C  2  b
d  4  D  1  a

#INNER

In [ ]:

D1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': [10,20,30,40,50]}, index= ['a','b', 'c','d', 'e'])
D2= pd.DataFrame( { 'C': ['A','B'], 'D': ['E', 'F']}, index= ['c','d'])
D1.join(D2, how= 'inner')

   A   B  C  D
c  3  30  A  E
d  4  40  B  F

##OUTER

In [ ]:

D1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': [10,20,30,40,50]}, index= ['a','b', 'c','d', 'e'])
D2= pd.DataFrame( { 'C': ['A','B'], 'D': ['E', 'F']}, index= ['c','d'])
D1.join(D2, how= 'outer')

   A   B    C    D
a  1  10  NaN  NaN
b  2  20  NaN  NaN
c  3  30    A    E
d  4  40    B    F
e  5  50  NaN  NaN

##LEFT

In [ ]:

D1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': [10,20,30,40,50]}, index= ['a','b', 'c','d', 'e'])
D2= pd.DataFrame( { 'C': ['A','B'], 'D': ['E', 'F']}, index= ['c','d'])
D1.join(D2, how= 'left')

   A   B    C    D
a  1  10  NaN  NaN
b  2  20  NaN  NaN
c  3  30    A    E
d  4  40    B    F
e  5  50  NaN  NaN

##RIGHT

In [ ]:

D1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': [10,20,30,40,50]}, index= ['a','b', 'c','d', 'e'])
D2= pd.DataFrame( { 'C': ['A','B'], 'D': ['E', 'F']}, index= ['c','d'])
D1.join(D2, how= 'right')

   A   B  C  D
c  3  30  A  E
d  4  40  B  F

##JOINING SAME NAME TABLES

In [ ]:
D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
D2= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['a','b','c','d']})
D1.join(D2, lsuffix= '_left', rsuffix= '_right')

   A_left B_left  A_right B_right
0       1      A        1       a
1       2      B        2       b
2       3      C        3       c
3       4      D        4       d